"""Run local GV3 model-search experiments on a fixed root-state dataset.

This is the second stage of the ModelSearchBed workflow.

High-level purpose:
    1. Load fixed root states generated by `root_storage.py`.
    2. Reuse an existing root dataset by default.
    3. Pass train/eval root records to `DNN/trainer.py`.
    4. Ask `DNN/infer.py` for model predictions on stored states.
    5. Compute train/eval MSE, MAE, and max absolute error in this harness.
    6. Record metrics to CSV so architectures/features can be compared.

Architecture-search boundary:
    This file should not decide the feature schema, model class, loss function,
    or inference representation. Agents trying new approaches should modify
    `DNN/infer.py`, model files, and `DNN/trainer.py`. This harness only owns
    fixed dataset generation/loading, deterministic splitting, and metric
    computation.

Fallback:
    Until custom hooks are added to `trainer.py` and `infer.py`, this file keeps
    a fallback adapter that uses the current GV3 `AlphaZeroModel` stack. That is
    only for smoke testing the harness.

Important scope:
    This file is for local architecture experiments. It should not use the GV3
    distributed network runner, SSH, or EC2 worker orchestration.
"""

from __future__ import annotations

import argparse
import csv
import json
import math
import random
from dataclasses import asdict, dataclass, field, replace
from pathlib import Path
from typing import Any

import torch

from ..DNN import infer as infer_module
from ..DNN import trainer as trainer_module
from ..DNN.dnn_spec import DEFAULT_DNN_SPEC
from ..DNN.infer import build_model_inputs
from ..DNN.trainer import Trainer, TrainerConfig
from ..DNN.value_models import AlphaZeroModel
from .root_storage import (
    DEFAULT_NONZERO_EPS,
    build_storage_config,
    generate_and_store_roots,
    make_local_env_and_mcts,
)


@dataclass(frozen=True)
class SelfModelTestConfig:
    """Configuration for one local model-search experiment."""

    dataset_dir: Path
    output_dir: Path

    # Dataset/root-storage settings. Existing datasets are reused by default.
    # Generation is only allowed when `allow_dataset_generation=True`.
    num_roots: int = 10_000
    max_candidate_roots: int = 100_000
    candidate_batch_size: int = 1_024
    min_nonzero_target_ratio: float = 0.50
    target_abs_threshold: float = DEFAULT_NONZERO_EPS
    history_hops_min: int = 0
    history_hops_max: int = 200
    seed: int = 2027
    num_processes: int = 1
    root_player_filter: str = "controller"
    allow_dataset_generation: bool = False

    # Train/eval split settings.
    eval_ratio: float = 0.20
    split_seed: int = 12345

    # Experiment identity and generic batching. Architecture/training-specific
    # settings live in `extra_config` so this harness does not constrain model
    # design choices.
    model_name: str = "baseline_value_model"
    batch_size: int = 256
    extra_config: dict[str, Any] = field(default_factory=dict)

    # Output/logging settings.
    metrics_csv_name: str = "self_model_test_metrics.csv"
    checkpoint_name: str = "best_model.pt"


@dataclass(frozen=True)
class DatasetSplit:
    """In-memory train/eval split of stored root records."""

    train_records: list[dict[str, Any]]
    eval_records: list[dict[str, Any]]


@dataclass(frozen=True)
class TrainArtifacts:
    """Objects produced by training a candidate architecture."""

    model: Any
    best_checkpoint_path: Path
    train_metrics: list[dict[str, Any]]


@dataclass(frozen=True)
class EvalResult:
    """Final evaluation summary for one trained model."""

    model_name: str
    trainable_params: int
    num_train_samples: int
    num_eval_samples: int
    train_mse: float
    train_rmse: float
    train_mae: float
    train_p50_abs_error: float
    train_p95_abs_error: float
    train_max_abs_error: float
    eval_mse: float
    eval_rmse: float
    eval_mae: float
    eval_p50_abs_error: float
    eval_p95_abs_error: float
    eval_max_abs_error: float


@dataclass(frozen=True)
class FeatureTensorDataset:
    """Fallback tensorized version of stored root records.

    This is intentionally only the fallback path for the existing GV3 model.
    New architecture experiments should avoid depending on this schema and
    should instead implement hooks in `trainer.py` and `infer.py`.
    """

    players: list[str]
    root_ids: list[int]
    prefill_req_features: torch.Tensor
    decode_req_features: torch.Tensor
    global_features: torch.Tensor
    prefill_req_mask: torch.Tensor | None
    decode_req_mask: torch.Tensor | None
    target_value: torch.Tensor

    def __len__(self) -> int:
        return int(self.target_value.shape[0])


class RootStateLoader:
    """Reusable local state loader for custom trainer/infer hooks.

    The hook API receives this object so architecture experiments can ask for a
    real GV3 state only when needed:

        state = state_loader(record)

    This avoids forcing `self_model_test.py` to choose features.
    """

    def __init__(self, cfg: SelfModelTestConfig) -> None:
        storage_cfg = build_storage_config(
            output_dir=cfg.dataset_dir,
            num_roots=max(1, int(cfg.num_roots)),
            max_candidate_roots=max(1, int(cfg.max_candidate_roots)),
            candidate_batch_size=max(1, int(cfg.candidate_batch_size)),
            min_nonzero_target_ratio=float(cfg.min_nonzero_target_ratio),
            target_abs_threshold=float(cfg.target_abs_threshold),
            history_hops_min=int(cfg.history_hops_min),
            history_hops_max=int(cfg.history_hops_max),
            seed=int(cfg.seed),
            root_player_filter="any",
            environment_lang="python",
            include_history_trace_logs=False,
            num_processes=1,
        )
        self.env, self.mcts = make_local_env_and_mcts(storage_cfg)

    def __call__(self, record: dict[str, Any]) -> Any:
        return _state_from_record(self.env, record)

    def close(self) -> None:
        if hasattr(self.mcts, "close"):
            self.mcts.close()


def build_self_model_test_config(
    *,
    dataset_dir: str | Path,
    output_dir: str | Path,
    num_roots: int = 10_000,
    max_candidate_roots: int = 100_000,
    candidate_batch_size: int = 1_024,
    min_nonzero_target_ratio: float = 0.50,
    target_abs_threshold: float = DEFAULT_NONZERO_EPS,
    history_hops_min: int = 0,
    history_hops_max: int = 200,
    seed: int = 2027,
    num_processes: int = 1,
    root_player_filter: str = "controller",
    allow_dataset_generation: bool = False,
    eval_ratio: float = 0.20,
    split_seed: int = 12345,
    model_name: str = "baseline_value_model",
    batch_size: int = 256,
    extra_config: dict[str, Any] | None = None,
) -> SelfModelTestConfig:
    """Create and validate config for a local self-model test run."""

    if int(num_roots) <= 0:
        raise ValueError("num_roots must be > 0")
    if int(max_candidate_roots) < int(num_roots):
        raise ValueError("max_candidate_roots must be >= num_roots")
    if int(candidate_batch_size) <= 0:
        raise ValueError("candidate_batch_size must be > 0")
    if not (0.0 <= float(min_nonzero_target_ratio) <= 1.0):
        raise ValueError("min_nonzero_target_ratio must be in [0, 1]")
    if float(target_abs_threshold) < 0.0:
        raise ValueError("target_abs_threshold must be >= 0")
    if int(history_hops_min) < 0 or int(history_hops_max) < int(history_hops_min):
        raise ValueError("history hop range is invalid")
    if int(num_processes) <= 0:
        raise ValueError("num_processes must be > 0")
    if str(root_player_filter) not in {"controller", "adversary", "any"}:
        raise ValueError("root_player_filter must be 'controller', 'adversary', or 'any'")
    if not (0.0 < float(eval_ratio) < 1.0):
        raise ValueError("eval_ratio must be in (0, 1)")
    if int(batch_size) <= 0:
        raise ValueError("batch_size must be > 0")
    if extra_config is not None and not isinstance(extra_config, dict):
        raise TypeError("extra_config must be a dict when provided")

    return SelfModelTestConfig(
        dataset_dir=Path(dataset_dir).expanduser(),
        output_dir=Path(output_dir).expanduser(),
        num_roots=int(num_roots),
        max_candidate_roots=int(max_candidate_roots),
        candidate_batch_size=int(candidate_batch_size),
        min_nonzero_target_ratio=float(min_nonzero_target_ratio),
        target_abs_threshold=float(target_abs_threshold),
        history_hops_min=int(history_hops_min),
        history_hops_max=int(history_hops_max),
        seed=int(seed),
        num_processes=int(num_processes),
        root_player_filter=str(root_player_filter),
        allow_dataset_generation=bool(allow_dataset_generation),
        eval_ratio=float(eval_ratio),
        split_seed=int(split_seed),
        model_name=str(model_name),
        batch_size=int(batch_size),
        extra_config=dict(extra_config or {}),
    )


def ensure_root_dataset(cfg: SelfModelTestConfig) -> Path:
    """Return an existing root dataset, or generate only when explicitly allowed.

    Expected behavior:
        - If `cfg.dataset_dir / "manifest.jsonl"` exists and has records, reuse it.
        - If the existing dataset has fewer than `cfg.num_roots`, still reuse it.
        - Only call `root_storage.generate_and_store_roots()` when the manifest is
          missing and `cfg.allow_dataset_generation=True`.
        - Generation should use local Python GV3 environment only.
        - The generated dataset should satisfy `cfg.min_nonzero_target_ratio`
          as much as possible, using the root-storage quota logic.
    """

    manifest = cfg.dataset_dir / "manifest.jsonl"
    if manifest.exists():
        record_count = _manifest_record_count(
            manifest,
            root_player_filter=str(cfg.root_player_filter),
        )
        if int(record_count) <= 0:
            raise ValueError(
                f"manifest exists but no records match root_player_filter="
                f"{cfg.root_player_filter!r}: {manifest}"
            )
        return cfg.dataset_dir

    if not bool(cfg.allow_dataset_generation):
        raise FileNotFoundError(
            f"root dataset manifest not found: {manifest}. "
            "Pass --allow-dataset-generation only when you intentionally want "
            "self_model_test.py to generate a new dataset."
        )

    storage_cfg = build_storage_config(
        output_dir=cfg.dataset_dir,
        num_roots=int(cfg.num_roots),
        max_candidate_roots=int(cfg.max_candidate_roots),
        candidate_batch_size=int(cfg.candidate_batch_size),
        min_nonzero_target_ratio=float(cfg.min_nonzero_target_ratio),
        target_abs_threshold=float(cfg.target_abs_threshold),
        history_hops_min=int(cfg.history_hops_min),
        history_hops_max=int(cfg.history_hops_max),
        seed=int(cfg.seed),
        root_player_filter=str(cfg.root_player_filter),
        environment_lang="python",
        include_history_trace_logs=True,
        num_processes=int(cfg.num_processes),
    )
    generate_and_store_roots(storage_cfg)
    return cfg.dataset_dir


def _manifest_record_count(manifest_path: Path, *, root_player_filter: str = "any") -> int:
    """Count records from a root-storage manifest without loading all shards."""

    total = 0
    player_filter = str(root_player_filter)
    try:
        with manifest_path.open("r", encoding="utf-8") as f:
            for line in f:
                if not line.strip():
                    continue
                row = json.loads(line)
                if player_filter == "any":
                    total += int(row.get("num_records", 0))
                else:
                    player_counts = row.get("player_counts", {})
                    total += int(player_counts.get(player_filter, 0))
    except Exception:
        return 0
    return int(total)


def load_root_records(cfg: SelfModelTestConfig) -> list[dict[str, Any]]:
    """Load stored root records from disk into memory.

    Each loaded record should contain:
        - simulator snapshot and stats
        - root player/depth metadata
        - target value
        - best action metadata
        - full history trace logs
    """

    ensure_root_dataset(cfg)
    return _load_matching_root_records(
        cfg.dataset_dir,
        root_player_filter=str(cfg.root_player_filter),
        max_roots=int(cfg.num_roots),
    )


def _load_matching_root_records(
    dataset_dir: str | Path,
    *,
    root_player_filter: str,
    max_roots: int,
) -> list[dict[str, Any]]:
    """Load only the requested number of matching records from root shards."""

    root_dir = Path(dataset_dir).expanduser()
    manifest = root_dir / "manifest.jsonl"
    if not manifest.exists():
        raise FileNotFoundError(f"manifest not found: {manifest}")

    player_filter = str(root_player_filter)
    records: list[dict[str, Any]] = []
    with manifest.open("r", encoding="utf-8") as f:
        for line in f:
            if not line.strip():
                continue
            entry = json.loads(line)
            shard_path = root_dir / str(entry["shard_path"])
            shard_records = torch.load(shard_path, map_location="cpu", weights_only=False)
            for record in shard_records:
                if player_filter != "any" and str(record.get("root_player", "")) != player_filter:
                    continue
                records.append(record)
                if len(records) >= int(max_roots):
                    return records
    return records


def split_records(
    records: list[dict[str, Any]],
    cfg: SelfModelTestConfig,
) -> DatasetSplit:
    """Split records into train/eval sets with deterministic shuffling."""

    if not records:
        raise ValueError("cannot split an empty record list")

    indices = list(range(len(records)))
    rng = random.Random(int(cfg.split_seed))
    rng.shuffle(indices)

    eval_count = int(round(float(len(indices)) * float(cfg.eval_ratio)))
    eval_count = max(1, min(len(indices) - 1, eval_count)) if len(indices) > 1 else 0

    eval_idx = set(indices[:eval_count])
    train_records = [records[i] for i in indices if i not in eval_idx]
    eval_records = [records[i] for i in indices if i in eval_idx]
    if not train_records:
        raise ValueError("train split is empty; use more records or lower eval_ratio")
    if not eval_records:
        raise ValueError("eval split is empty; use more records or higher eval_ratio")
    return DatasetSplit(train_records=train_records, eval_records=eval_records)


def _state_from_record(env: Any, record: dict[str, Any]) -> Any:
    """Rebuild a GV3 state object from one stored root record."""

    snapshot = record["simulator_snapshot"]
    stats = record["stats"]
    clone_fn = getattr(env, "clone_state_from_snapshot", None)
    if callable(clone_fn):
        return clone_fn(snapshot, stats)

    state = env.initial_state()
    state.simulator.restore_state(snapshot)
    state.stats = stats.clone()
    return state


def build_feature_dataset(
    records: list[dict[str, Any]],
    cfg: SelfModelTestConfig,
) -> Any:
    """Fallback: convert stored root records into current GV3 tensors.

    This is not the abstraction agents should depend on. It only keeps the
    current GV3 architecture runnable as a smoke test. Custom architectures
    should implement trainer/infer hooks and decide their own features.
    """

    if not records:
        raise ValueError("cannot build features from an empty record list")

    storage_cfg = build_storage_config(
        output_dir=cfg.dataset_dir,
        num_roots=max(1, int(cfg.num_roots)),
        max_candidate_roots=max(1, int(cfg.max_candidate_roots)),
        candidate_batch_size=max(1, int(cfg.candidate_batch_size)),
        min_nonzero_target_ratio=float(cfg.min_nonzero_target_ratio),
        target_abs_threshold=float(cfg.target_abs_threshold),
        history_hops_min=int(cfg.history_hops_min),
        history_hops_max=int(cfg.history_hops_max),
        seed=int(cfg.seed),
        root_player_filter="any",
        environment_lang="python",
        include_history_trace_logs=False,
    )
    env, mcts = make_local_env_and_mcts(storage_cfg)

    players: list[str] = []
    root_ids: list[int] = []
    prefill_features: list[torch.Tensor] = []
    decode_features: list[torch.Tensor] = []
    global_features: list[torch.Tensor] = []
    prefill_masks: list[torch.Tensor] = []
    decode_masks: list[torch.Tensor] = []
    targets: list[float] = []

    try:
        for record in records:
            player = str(record["root_player"])
            state = _state_from_record(env, record)
            inputs = build_model_inputs(state, player, torch.device("cpu"))

            players.append(player)
            root_ids.append(int(record["root_id"]))
            prefill_features.append(inputs.prefill_req_features.squeeze(0).detach().cpu())
            decode_features.append(inputs.decode_req_features.squeeze(0).detach().cpu())
            global_features.append(inputs.global_features.squeeze(0).detach().cpu())
            if inputs.prefill_req_mask is None:
                prefill_masks.append(torch.ones(inputs.prefill_req_features.shape[1], dtype=torch.bool))
            else:
                prefill_masks.append(inputs.prefill_req_mask.squeeze(0).detach().cpu().to(dtype=torch.bool))
            if inputs.decode_req_mask is None:
                decode_masks.append(torch.ones(inputs.decode_req_features.shape[1], dtype=torch.bool))
            else:
                decode_masks.append(inputs.decode_req_mask.squeeze(0).detach().cpu().to(dtype=torch.bool))
            targets.append(float(record["target_value"]))
    finally:
        if hasattr(mcts, "close"):
            mcts.close()

    return FeatureTensorDataset(
        players=players,
        root_ids=root_ids,
        prefill_req_features=torch.stack(prefill_features, dim=0),
        decode_req_features=torch.stack(decode_features, dim=0),
        global_features=torch.stack(global_features, dim=0),
        prefill_req_mask=torch.stack(prefill_masks, dim=0),
        decode_req_mask=torch.stack(decode_masks, dim=0),
        target_value=torch.tensor(targets, dtype=torch.float32),
    )


def _extra(cfg: SelfModelTestConfig, key: str, default: Any) -> Any:
    """Read a model/training-specific setting without making it harness API."""

    return cfg.extra_config.get(key, default)


def _extra_int(cfg: SelfModelTestConfig, key: str, default: int) -> int:
    return int(_extra(cfg, key, default))


def _extra_float(cfg: SelfModelTestConfig, key: str, default: float) -> float:
    return float(_extra(cfg, key, default))


def _fallback_device(cfg: SelfModelTestConfig) -> torch.device:
    return torch.device(str(_extra(cfg, "device", "cpu")))


def build_candidate_gv3_model(cfg: SelfModelTestConfig) -> Any:
    """Fallback-only constructor for the current GV3 AlphaZeroModel stack.

    Custom architecture experiments should implement `trainer.py` /
    `infer.py` hooks instead of depending on this function.
    """

    d_req_emb = _extra_int(cfg, "d_req_emb", 32)
    d_trunk = _extra_int(cfg, "d_trunk", 64)
    num_attention_heads = _extra_int(cfg, "num_attention_heads", 4)
    num_attention_layers = _extra_int(cfg, "num_attention_layers", 1)
    dropout_p = _extra_float(cfg, "dropout_p", 0.05)
    max_trainable_params = _extra_int(cfg, "max_trainable_params", 150_000)

    if d_req_emb <= 0 or d_trunk <= 0:
        raise ValueError("fallback GV3 model dimensions must be > 0")
    if num_attention_heads <= 0 or num_attention_layers <= 0:
        raise ValueError("fallback GV3 attention settings must be > 0")
    if d_req_emb % num_attention_heads != 0:
        raise ValueError("fallback d_req_emb must be divisible by num_attention_heads")
    if not (0.0 <= dropout_p < 1.0):
        raise ValueError("fallback dropout_p must be in [0, 1)")
    if max_trainable_params <= 0:
        raise ValueError("fallback max_trainable_params must be > 0")

    spec = replace(
        DEFAULT_DNN_SPEC,
        d_req_emb=int(d_req_emb),
        d_global_emb=int(d_req_emb),
        d_trunk=int(d_trunk),
        num_attention_heads=int(num_attention_heads),
        num_attention_layers=int(num_attention_layers),
        dropout_p=float(dropout_p),
    )
    spec.validate()
    model = AlphaZeroModel(spec=spec)
    params = count_trainable_parameters(model)
    if int(params) > int(max_trainable_params):
        raise ValueError(
            f"model has {params} trainable params, above budget {max_trainable_params}"
        )
    return model


def count_trainable_parameters(model: Any) -> int:
    """Return the number of trainable parameters in the candidate model."""

    attr = getattr(model, "trainable_params", None)
    if attr is not None:
        return int(attr)
    params_fn = getattr(model, "parameters", None)
    if not callable(params_fn):
        return 0
    return int(sum(p.numel() for p in params_fn() if getattr(p, "requires_grad", False)))


def _iter_index_batches(n: int, batch_size: int, *, shuffle: bool, seed: int) -> list[list[int]]:
    indices = list(range(int(n)))
    if shuffle:
        random.Random(int(seed)).shuffle(indices)
    return [indices[i : i + int(batch_size)] for i in range(0, len(indices), int(batch_size))]


def _batch_by_player(
    dataset: FeatureTensorDataset,
    indices: list[int],
    device: torch.device,
) -> dict[str, dict[str, torch.Tensor] | None]:
    out: dict[str, dict[str, torch.Tensor] | None] = {"controller": None, "adversary": None}
    for player in ("controller", "adversary"):
        idxs = [i for i in indices if dataset.players[i] == player]
        if not idxs:
            continue
        t = torch.tensor(idxs, dtype=torch.long)
        out[player] = {
            "prefill_req_features": dataset.prefill_req_features.index_select(0, t).to(device),
            "decode_req_features": dataset.decode_req_features.index_select(0, t).to(device),
            "global_features": dataset.global_features.index_select(0, t).to(device),
            "prefill_req_mask": (
                None
                if dataset.prefill_req_mask is None
                else dataset.prefill_req_mask.index_select(0, t).to(device)
            ),
            "decode_req_mask": (
                None
                if dataset.decode_req_mask is None
                else dataset.decode_req_mask.index_select(0, t).to(device)
            ),
            "target_value": dataset.target_value.index_select(0, t).to(device),
        }
    return out


@torch.no_grad()
def _eval_loss_with_gv3_trainer(
    trainer: Trainer,
    dataset: FeatureTensorDataset,
    cfg: SelfModelTestConfig,
    device: torch.device,
) -> dict[str, float]:
    total: dict[str, float] = {}
    total_count = 0
    for indices in _iter_index_batches(len(dataset), cfg.batch_size, shuffle=False, seed=0):
        batch = _batch_by_player(dataset, indices, device)
        stats = trainer.eval_step(batch)
        count = len(indices)
        total_count += count
        for key, value in stats.items():
            if key.endswith("_count") or key == "step":
                continue
            total[key] = total.get(key, 0.0) + float(value) * count

    if total_count <= 0:
        raise RuntimeError("empty eval dataset")
    return {key: value / float(total_count) for key, value in total.items()}


def _normalize_train_artifacts(obj: Any, cfg: SelfModelTestConfig) -> TrainArtifacts:
    """Normalize custom trainer hook output into `TrainArtifacts`.

    Supported custom hook returns:
        - TrainArtifacts
        - {"model": ..., "best_checkpoint_path": ..., "train_metrics": [...]}
        - (model, train_metrics)
    """

    if isinstance(obj, TrainArtifacts):
        return obj
    if isinstance(obj, dict):
        model = obj.get("model")
        if model is None:
            raise ValueError("trainer hook returned dict without 'model'")
        ckpt = Path(obj.get("best_checkpoint_path", cfg.output_dir / cfg.checkpoint_name))
        metrics = list(obj.get("train_metrics", []))
        return TrainArtifacts(model=model, best_checkpoint_path=ckpt, train_metrics=metrics)
    if isinstance(obj, tuple) and len(obj) >= 1:
        model = obj[0]
        metrics = list(obj[1]) if len(obj) >= 2 and obj[1] is not None else []
        return TrainArtifacts(
            model=model,
            best_checkpoint_path=cfg.output_dir / cfg.checkpoint_name,
            train_metrics=metrics,
        )
    raise TypeError(f"unsupported trainer hook return type: {type(obj)!r}")


def _fallback_train_current_gv3_model(
    train_records: list[dict[str, Any]],
    eval_records: list[dict[str, Any]],
    cfg: SelfModelTestConfig,
) -> TrainArtifacts:
    """Fallback trainer for the existing GV3 AlphaZeroModel stack.

    This path intentionally lives behind the hook mechanism. It proves the
    harness works, but it is not meant to constrain future architecture agents.
    """

    train_dataset = build_feature_dataset(train_records, cfg)
    eval_dataset = build_feature_dataset(eval_records, cfg)

    cfg.output_dir.mkdir(parents=True, exist_ok=True)
    device = _fallback_device(cfg)
    num_epochs = _extra_int(cfg, "num_epochs", 50)
    learning_rate = _extra_float(cfg, "learning_rate", 1e-3)
    weight_decay = _extra_float(cfg, "weight_decay", 0.0)
    if num_epochs <= 0:
        raise ValueError("fallback num_epochs must be > 0")
    if learning_rate <= 0.0:
        raise ValueError("fallback learning_rate must be > 0")
    if weight_decay < 0.0:
        raise ValueError("fallback weight_decay must be >= 0")

    model = build_candidate_gv3_model(cfg)
    model.to(device)

    trainer = Trainer(
        model,
        cfg=TrainerConfig(
            lr=float(learning_rate),
            weight_decay=float(weight_decay),
            policy_weight=0.0,
            value_weight=1.0,
            value_only=True,
        ),
        device=device,
    )

    best_path = cfg.output_dir / cfg.checkpoint_name
    metrics: list[dict[str, Any]] = []
    params = count_trainable_parameters(model)

    for epoch in range(1, int(num_epochs) + 1):
        batch_metrics: list[dict[str, float]] = []
        for indices in _iter_index_batches(
            len(train_dataset),
            int(cfg.batch_size),
            shuffle=True,
            seed=int(cfg.seed) + int(epoch),
        ):
            batch = _batch_by_player(train_dataset, indices, device)
            batch_metrics.append(trainer.train_step(batch))

        train_loss = sum(float(m["loss"]) for m in batch_metrics) / max(1, len(batch_metrics))
        train_value_mse = sum(float(m["value_mse_error"]) for m in batch_metrics) / max(1, len(batch_metrics))
        train_value_mae = sum(float(m["value_mae_error"]) for m in batch_metrics) / max(1, len(batch_metrics))
        eval_stats = _eval_loss_with_gv3_trainer(trainer, eval_dataset, cfg, device)
        saved_best = trainer.maybe_save_best(float(eval_stats["loss"]), best_path)

        metrics.append(
            {
                "epoch": int(epoch),
                "model_name": str(cfg.model_name),
                "trainable_params": int(params),
                "train_loss": float(train_loss),
                "train_value_mse_error": float(train_value_mse),
                "train_value_mae_error": float(train_value_mae),
                "eval_loss": float(eval_stats["loss"]),
                "eval_value_loss": float(eval_stats["value_loss"]),
                "eval_value_mse_error": float(eval_stats["value_mse_error"]),
                "eval_value_mae_error": float(eval_stats["value_mae_error"]),
                "saved_best": bool(saved_best),
                "backend": "fallback_current_gv3",
            }
        )

    if best_path.exists():
        checkpoint = torch.load(best_path, map_location=device, weights_only=False)
        model.load_state_dict(checkpoint["model_state"])

    return TrainArtifacts(
        model=model,
        best_checkpoint_path=best_path,
        train_metrics=metrics,
    )


def train_candidate_model(
    train_records: list[dict[str, Any]],
    eval_records: list[dict[str, Any]],
    cfg: SelfModelTestConfig,
    state_loader: RootStateLoader,
) -> TrainArtifacts:
    """Train one candidate model on fixed root records.

    Expected behavior:
        - Prefer `DNN/trainer.py::train_model_search(...)` when present.
        - Pass raw root records and a `state_loader` into that hook.
        - Let trainer/model files choose features, architecture, loss, epochs,
          and optimizer details.
        - Fall back to current GV3 AlphaZeroModel only when no hook exists.
    """

    hook = getattr(trainer_module, "train_model_search", None)
    if callable(hook):
        artifacts = hook(
            train_records=train_records,
            eval_records=eval_records,
            cfg=cfg,
            state_loader=state_loader,
            output_dir=cfg.output_dir,
        )
        return _normalize_train_artifacts(artifacts, cfg)

    return _fallback_train_current_gv3_model(train_records, eval_records, cfg)


def _fallback_predict_current_gv3_model(
    model: Any,
    records: list[dict[str, Any]],
    cfg: SelfModelTestConfig,
) -> list[float]:
    """Fallback inference for the existing GV3 AlphaZeroModel stack."""

    dataset = build_feature_dataset(records, cfg)
    device = _fallback_device(cfg)
    if hasattr(model, "to"):
        model = model.to(device)
    if hasattr(model, "eval"):
        model.eval()

    predictions: list[float] = []
    with torch.no_grad():
        for indices in _iter_index_batches(len(dataset), cfg.batch_size, shuffle=False, seed=0):
            for player in ("controller", "adversary"):
                idxs = [i for i in indices if dataset.players[i] == player]
                if not idxs:
                    continue
                t = torch.tensor(idxs, dtype=torch.long)
                _policy, value_raw = model.forward(
                    player=player,
                    prefill_req_features=dataset.prefill_req_features.index_select(0, t).to(device),
                    decode_req_features=dataset.decode_req_features.index_select(0, t).to(device),
                    global_features=dataset.global_features.index_select(0, t).to(device),
                    prefill_req_mask=(
                        None
                        if dataset.prefill_req_mask is None
                        else dataset.prefill_req_mask.index_select(0, t).to(device)
                    ),
                    decode_req_mask=(
                        None
                        if dataset.decode_req_mask is None
                        else dataset.decode_req_mask.index_select(0, t).to(device)
                    ),
                    action_mask=None,
                )
                pred = model.value_scalar_from_logits(value_raw).view(-1).cpu()
                predictions.extend(float(x) for x in pred.tolist())
    return predictions


def predict_candidate_values(
    model: Any,
    records: list[dict[str, Any]],
    cfg: SelfModelTestConfig,
    state_loader: RootStateLoader,
    *,
    split_name: str,
) -> list[float]:
    """Predict values for records using `infer.py` when possible.

    Preferred custom hook:

        DNN/infer.py::predict_model_search_values(
            model=model,
            records=records,
            cfg=cfg,
            state_loader=state_loader,
            split_name="train" | "eval",
        ) -> list[float] or {"predictions": list[float]}

    The hook can use raw records, reconstructed states, custom features, a
    decision tree, a torch model, or anything else. This harness only requires
    one real-scale prediction per record.
    """

    hook = getattr(infer_module, "predict_model_search_values", None)
    if callable(hook):
        out = hook(
            model=model,
            records=records,
            cfg=cfg,
            state_loader=state_loader,
            split_name=str(split_name),
        )
        if isinstance(out, dict):
            out = out.get("predictions", [])
        preds = [float(x) for x in list(out)]
        if len(preds) != len(records):
            raise ValueError(
                f"infer hook returned {len(preds)} predictions for {len(records)} records"
            )
        return preds

    preds = _fallback_predict_current_gv3_model(model, records, cfg)
    if len(preds) != len(records):
        raise ValueError(f"fallback returned {len(preds)} predictions for {len(records)} records")
    return preds


def _error_metrics(records: list[dict[str, Any]], predictions: list[float]) -> dict[str, float]:
    """Compute real-scale error metrics for one split."""

    if len(records) != len(predictions):
        raise ValueError(f"records/predictions length mismatch: {len(records)} != {len(predictions)}")
    if not records:
        raise ValueError("cannot evaluate an empty split")

    errors = [
        float(pred) - float(record["target_value"])
        for record, pred in zip(records, predictions)
    ]
    err_t = torch.tensor(errors, dtype=torch.float32)
    abs_t = torch.abs(err_t)
    mse = float(torch.mean(err_t * err_t).item())
    mae = float(torch.mean(abs_t).item())
    sorted_abs = torch.sort(abs_t).values

    def percentile(p: float) -> float:
        if sorted_abs.numel() == 0:
            return float("nan")
        pos = min(sorted_abs.numel() - 1, max(0, int(math.ceil(float(p) * sorted_abs.numel()) - 1)))
        return float(sorted_abs[pos].item())

    return {
        "mse": float(mse),
        "rmse": float(math.sqrt(mse)),
        "mae": float(mae),
        "p50_abs_error": percentile(0.50),
        "p95_abs_error": percentile(0.95),
        "max_abs_error": float(torch.max(abs_t).item()),
    }


def evaluate_candidate_model(
    model: Any,
    train_records: list[dict[str, Any]],
    eval_records: list[dict[str, Any]],
    cfg: SelfModelTestConfig,
    state_loader: RootStateLoader,
) -> EvalResult:
    """Evaluate the trained model on train and held-out eval records.

    This harness only evaluates predictions. It does not know how features were
    built or how the model works. Those details belong in `infer.py`.
    """

    train_pred = predict_candidate_values(
        model,
        train_records,
        cfg,
        state_loader,
        split_name="train",
    )
    eval_pred = predict_candidate_values(
        model,
        eval_records,
        cfg,
        state_loader,
        split_name="eval",
    )
    train_metrics = _error_metrics(train_records, train_pred)
    eval_metrics = _error_metrics(eval_records, eval_pred)

    return EvalResult(
        model_name=str(cfg.model_name),
        trainable_params=int(count_trainable_parameters(model)),
        num_train_samples=int(len(train_records)),
        num_eval_samples=int(len(eval_records)),
        train_mse=float(train_metrics["mse"]),
        train_rmse=float(train_metrics["rmse"]),
        train_mae=float(train_metrics["mae"]),
        train_p50_abs_error=float(train_metrics["p50_abs_error"]),
        train_p95_abs_error=float(train_metrics["p95_abs_error"]),
        train_max_abs_error=float(train_metrics["max_abs_error"]),
        eval_mse=float(eval_metrics["mse"]),
        eval_rmse=float(eval_metrics["rmse"]),
        eval_mae=float(eval_metrics["mae"]),
        eval_p50_abs_error=float(eval_metrics["p50_abs_error"]),
        eval_p95_abs_error=float(eval_metrics["p95_abs_error"]),
        eval_max_abs_error=float(eval_metrics["max_abs_error"]),
    )


def write_training_metrics(
    metrics: list[dict[str, Any]],
    cfg: SelfModelTestConfig,
) -> Path:
    """Write per-epoch training/eval metrics to CSV."""

    cfg.output_dir.mkdir(parents=True, exist_ok=True)
    path = cfg.output_dir / cfg.metrics_csv_name
    if not metrics:
        return path
    fieldnames = sorted({key for row in metrics for key in row.keys()})
    with path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(metrics)
    return path


def append_eval_summary(
    result: EvalResult,
    cfg: SelfModelTestConfig,
) -> Path:
    """Append final model evaluation summary to CSV."""

    cfg.output_dir.mkdir(parents=True, exist_ok=True)
    path = cfg.output_dir / "self_model_test_eval_summary.csv"
    row = asdict(result)
    row.update(
        {
            "dataset_dir": str(cfg.dataset_dir),
            "num_roots": int(cfg.num_roots),
            "min_nonzero_target_ratio": float(cfg.min_nonzero_target_ratio),
            "target_abs_threshold": float(cfg.target_abs_threshold),
            "history_hops_min": int(cfg.history_hops_min),
            "history_hops_max": int(cfg.history_hops_max),
            "num_processes": int(cfg.num_processes),
            "root_player_filter": str(cfg.root_player_filter),
            "allow_dataset_generation": bool(cfg.allow_dataset_generation),
            "batch_size": int(cfg.batch_size),
            "extra_config_json": json.dumps(cfg.extra_config, sort_keys=True),
        }
    )
    exists = path.exists()
    with path.open("a", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(row.keys()))
        if not exists:
            writer.writeheader()
        writer.writerow(row)
    return path


def run_self_model_test(cfg: SelfModelTestConfig) -> EvalResult:
    """Full local model-search workflow.

    Flow:
        1. Ensure/load fixed root dataset.
        2. Split into train/eval.
        3. Create a reusable state loader.
        4. Call trainer hook or fallback trainer.
        5. Call infer hook or fallback inference.
        6. Evaluate train/eval errors.
        7. Write metrics and return final summary.
    """

    cfg.output_dir.mkdir(parents=True, exist_ok=True)
    records = load_root_records(cfg)
    split = split_records(records, cfg)
    state_loader = RootStateLoader(cfg)
    try:
        artifacts = train_candidate_model(
            split.train_records,
            split.eval_records,
            cfg,
            state_loader,
        )
        result = evaluate_candidate_model(
            artifacts.model,
            split.train_records,
            split.eval_records,
            cfg,
            state_loader,
        )
        write_training_metrics(artifacts.train_metrics, cfg)
        append_eval_summary(result, cfg)
        return result
    finally:
        state_loader.close()


def parse_args() -> SelfModelTestConfig:
    """Parse CLI args and return `SelfModelTestConfig`."""

    parser = argparse.ArgumentParser(description="Run local GV3 ModelSearchBed value-model test.")
    parser.add_argument("--dataset-dir", required=True)
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--num-roots", type=int, default=10_000)
    parser.add_argument("--max-candidate-roots", type=int, default=100_000)
    parser.add_argument("--candidate-batch-size", type=int, default=1_024)
    parser.add_argument("--min-nonzero-target-ratio", type=float, default=0.50)
    parser.add_argument("--target-abs-threshold", type=float, default=DEFAULT_NONZERO_EPS)
    parser.add_argument("--history-hops-min", type=int, default=0)
    parser.add_argument("--history-hops-max", type=int, default=200)
    parser.add_argument("--seed", type=int, default=2027)
    parser.add_argument("--num-processes", type=int, default=1)
    parser.add_argument("--root-player-filter", choices=("controller", "adversary", "any"), default="controller")
    parser.add_argument(
        "--allow-dataset-generation",
        action="store_true",
        help="Generate a dataset when --dataset-dir has no manifest. Off by default.",
    )
    parser.add_argument("--eval-ratio", type=float, default=0.20)
    parser.add_argument("--split-seed", type=int, default=12345)
    parser.add_argument("--model-name", default="baseline_value_model")
    parser.add_argument("--batch-size", type=int, default=256)
    parser.add_argument(
        "--extra-config-json",
        default="{}",
        help="Free-form JSON object passed through to trainer/infer hooks.",
    )
    args = parser.parse_args()
    extra_config = json.loads(args.extra_config_json)
    if not isinstance(extra_config, dict):
        raise ValueError("--extra-config-json must decode to a JSON object")
    return build_self_model_test_config(
        dataset_dir=args.dataset_dir,
        output_dir=args.output_dir,
        num_roots=args.num_roots,
        max_candidate_roots=args.max_candidate_roots,
        candidate_batch_size=args.candidate_batch_size,
        min_nonzero_target_ratio=args.min_nonzero_target_ratio,
        target_abs_threshold=args.target_abs_threshold,
        history_hops_min=args.history_hops_min,
        history_hops_max=args.history_hops_max,
        seed=args.seed,
        num_processes=args.num_processes,
        root_player_filter=args.root_player_filter,
        allow_dataset_generation=bool(args.allow_dataset_generation),
        eval_ratio=args.eval_ratio,
        split_seed=args.split_seed,
        model_name=args.model_name,
        batch_size=args.batch_size,
        extra_config=extra_config,
    )


def main() -> None:
    """CLI entrypoint for local self-model tests."""

    cfg = parse_args()
    run_self_model_test(cfg)


if __name__ == "__main__":
    main()
