#!/usr/bin/env bash

# Shared runtime contract for the EXP3 500-MCTS, leaf-relative 1-second-rollout
# experiment.
# Source this file before invoking vidur.AlphaGoZero.deploy. The deploy helper
# forwards these variables to the XL coordinator and every worker daemon.

export AGZ_CLUSTER=exp3
export AGZ_REMOTE_OUTPUT_ROOT=/home/ubuntu/vidur-classical-search/simulator_output/GV3_Agent/AlphaGoZero_EXP3_UNTRAINED_.995_500_MCTS_1s_LEAF_RELATIVE_ROLLOUT_DNN

export AGZ_MODEL_FAMILY=dnn
export AGZ_VALUE_FEATURE_SCHEMA=markov_v2
export AGZ_DNN_EPOCHS=5
export AGZ_DNN_VALUE_BATCH_SIZE=4096
export AGZ_DNN_POLICY_ROOT_BATCH_SIZE=256
export AGZ_DNN_INITIAL_LR=0.0003
export AGZ_DNN_UPDATE_LR=0.0001
export AGZ_DNN_TORCH_THREADS_PER_MODEL=24

export AGZ_MCTS_ITERATIONS=500
export AGZ_EVAL_MCTS_ITERATIONS=500
export AGZ_SELFPLAY_ARENA_TIME_LIMIT_SEC=5
export AGZ_DISCOUNT_FACTOR=0.995
export AGZ_ROOT_DIRICHLET_ALPHA=0.05
export AGZ_ROOT_DIRICHLET_EPSILON=0.25
export AGZ_INITIAL_SAMPLE_MOVE_COUNT=20

export AGZ_NATIVE_SEARCH_MODE=full_tree_rollout
export AGZ_ROLLOUT_COUNT=10
export AGZ_EVAL_ROLLOUT_COUNT=8
export AGZ_SJF_ROLLOUT_COUNT=3
export AGZ_ROLLOUT_PARALLEL_THREADS=1
export AGZ_EVAL_ROLLOUT_PARALLEL_THREADS=2
export AGZ_SJF_ROLLOUT_PARALLEL_THREADS=3
export AGZ_ROLLOUT_HORIZON_SEC=1.0
export AGZ_ROLLOUT_POLICY_TEMPERATURE=1.0
export AGZ_ROLLOUT_PROBABILITY_QUANTUM=0.000001
export AGZ_ROLLOUT_MAX_ACTIONS=4096

export AGZ_TRAIN_TRIGGER_NEW_STATES=50000
export AGZ_MIN_CONTROLLER_STATES_FOR_EVAL=100000
export AGZ_MIN_ADVERSARY_STATES_FOR_EVAL=50000
export AGZ_CONTROLLER_POLICY_SAMPLE_CAP=100000
export AGZ_ADVERSARY_POLICY_SAMPLE_CAP=50000
export AGZ_TRAIN_SAMPLE_MIN_MID_REPLAY=50000
export AGZ_TRAIN_SAMPLE_MIN_LARGE_REPLAY=100000
export AGZ_MAX_VALUE_STATES=900000
export AGZ_MAX_ADVERSARY_VALUE_STATES=300000
export AGZ_POLICY_ROOT_OVERSAMPLE_FACTOR=1.25
export AGZ_POLICY_CACHE_BUILD_WORKERS=60

export AGZ_XL_MAX_REPLAY_STATES=35000000
export AGZ_XL_CONTROLLER_MAX_REPLAY_STATES=20000000
export AGZ_XL_ADVERSARY_MAX_REPLAY_STATES=15000000
export AGZ_XL_MAX_INGEST_SHARDS_PER_LOOP=0
export AGZ_XL_PAUSE_INGEST_WHILE_PRUNE_DEFERRED=0

export AGZ_PROMOTION_WIN_RATE_THRESHOLD=0.58
export AGZ_ROLE_PROMOTION_WIN_THRESHOLD=57
export AGZ_MAX_PROMOTIONS=50
export AGZ_TRAIN_FAILURE_BACKOFF_SEC=600

# Evaluation pauses self-play, samples live CPU/RAM, and fails closed unless the
# entire phase fits one wave. Role evaluation uses two rollout threads per game;
# SJF uses three, matching its three rollout trajectories. Both settings consume
# otherwise idle cores to reduce the latency of the final straggler games.
# The CPU sets already retain four XL cores and two worker cores, so no second
# numeric CPU reserve is applied inside those sets.
export AGZ_DISTRIBUTED_EVAL_GAME_MEMORY_GIB=1.5
export AGZ_DISTRIBUTED_EVAL_MEMORY_RESERVE_GIB=18.5
export AGZ_DISTRIBUTED_EVAL_MEMORY_RESERVE_FRACTION=0.25
export AGZ_DISTRIBUTED_EVAL_PAUSE_SELFPLAY=1
export AGZ_DISTRIBUTED_EVAL_PAUSE_TIMEOUT_SEC=30
export AGZ_DISTRIBUTED_EVAL_ROLE_THREADS_PER_GAME=2
export AGZ_DISTRIBUTED_EVAL_SJF_THREADS_PER_GAME=3
export AGZ_DISTRIBUTED_EVAL_CPU_RESERVE_CORES=0
export AGZ_DISTRIBUTED_EVAL_CPU_RESERVE_FRACTION=0
export AGZ_DISTRIBUTED_EVAL_CPU_SAMPLE_SEC=0.25
export AGZ_DISTRIBUTED_EVAL_XL_GAMES=32
export AGZ_DISTRIBUTED_EVAL_XL_PARALLEL=60
export AGZ_DISTRIBUTED_EVAL_XL_CPUSET=4-95
export AGZ_DISTRIBUTED_EVAL_WORKER_PARALLEL=60
export AGZ_DISTRIBUTED_EVAL_WORKER_CPUSET=2-95
export AGZ_DISTRIBUTED_EVAL_SJF_WORKER_GAMES=5
export AGZ_DISTRIBUTED_EVAL_SJF_HOST_PARALLEL=12

# Sixty one-thread self-play processes matched or exceeded the aggregate
# throughput of 60 two-thread processes and leave 36 CPUs for system work.
export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
