#!/usr/bin/env bash

# EXP3 leaf-relative rollout experiment:
# - neutral/untrained Markov-v2 DNN v100
# - 1,000 MCTS simulations per non-trivial decision
# - one policy-guided continuation per expanded leaf
# - five-second leaf-relative rollout horizon
# - five-second self-play trajectory and replay target window
# - gamma=0.99
#
# The requested output directory contains "500_MCTS", but the runtime contract
# intentionally uses 1,000 simulations as explicitly requested.

export AGZ_CLUSTER=exp3
export AGZ_REMOTE_OUTPUT_ROOT=/home/ubuntu/vidur-classical-search/simulator_output/GV3_Agent/AlphaGoZero_EXP3_UNTRAINED_.99_500_MCTS_5s_LEAF_RELATIVE_ROLLOUT_DNN

export AGZ_MODEL_FAMILY=dnn
export AGZ_VALUE_FEATURE_SCHEMA=markov_v2
export AGZ_DNN_EPOCHS=5
export AGZ_DNN_VALUE_BATCH_SIZE=4096
export AGZ_DNN_POLICY_ROOT_BATCH_SIZE=256
export AGZ_DNN_INITIAL_LR=0.0003
export AGZ_DNN_UPDATE_LR=0.0001
export AGZ_DNN_TORCH_THREADS_PER_MODEL=24

export AGZ_MCTS_ITERATIONS=1000
export AGZ_EVAL_MCTS_ITERATIONS=1000
export AGZ_SELFPLAY_ARENA_TIME_LIMIT_SEC=5
export AGZ_REPLAY_SAMPLE_WINDOW_SEC=5
export AGZ_DISCOUNT_FACTOR=0.99
export AGZ_ROOT_DIRICHLET_ALPHA=0.05
export AGZ_ROOT_DIRICHLET_EPSILON=0.25
export AGZ_INITIAL_SAMPLE_MOVE_COUNT=20

export AGZ_NATIVE_SEARCH_MODE=full_tree_rollout
export AGZ_ROLLOUT_COUNT=1
export AGZ_EVAL_ROLLOUT_COUNT=1
export AGZ_SJF_ROLLOUT_COUNT=1
export AGZ_ROLLOUT_PARALLEL_THREADS=1
export AGZ_EVAL_ROLLOUT_PARALLEL_THREADS=1
export AGZ_SJF_ROLLOUT_PARALLEL_THREADS=1
export AGZ_ROLLOUT_HORIZON_SEC=5.0
export AGZ_ROLLOUT_POLICY_TEMPERATURE=1.0
export AGZ_ROLLOUT_PROBABILITY_QUANTUM=0.000001
export AGZ_ROLLOUT_MAX_ACTIONS=4096

export AGZ_TRAIN_TRIGGER_NEW_STATES=100000
export AGZ_MIN_CONTROLLER_STATES_FOR_EVAL=100000
export AGZ_MIN_ADVERSARY_STATES_FOR_EVAL=50000
export AGZ_CONTROLLER_POLICY_SAMPLE_CAP=100000
export AGZ_ADVERSARY_POLICY_SAMPLE_CAP=50000
export AGZ_TRAIN_SAMPLE_MIN_MID_REPLAY=50000
export AGZ_TRAIN_SAMPLE_MIN_LARGE_REPLAY=100000
export AGZ_MAX_VALUE_STATES=900000
export AGZ_MAX_ADVERSARY_VALUE_STATES=300000

export AGZ_REPLAY_SAMPLER=indexed_v1
export AGZ_REPLAY_INDEX_BUILD_WORKERS=60
export AGZ_REPLAY_EXTRACTION_WORKERS=16
export AGZ_POLICY_CACHE_BUILD_WORKERS=60

export AGZ_XL_MAX_REPLAY_STATES=35000000
export AGZ_XL_CONTROLLER_MAX_REPLAY_STATES=20000000
export AGZ_XL_ADVERSARY_MAX_REPLAY_STATES=15000000
export AGZ_XL_MAX_INGEST_SHARDS_PER_LOOP=0
export AGZ_XL_PAUSE_INGEST_WHILE_PRUNE_DEFERRED=0

# Each role uses a separate 140-game block. Promotion is strict wins > 81.
export AGZ_EVAL_GAMES=140
export AGZ_BENCHMARK_GAMES=50
export AGZ_PROMOTION_WIN_RATE_THRESHOLD=0.57
export AGZ_ROLE_PROMOTION_WIN_THRESHOLD=81
export AGZ_MAX_PROMOTIONS=50
export AGZ_TRAIN_FAILURE_BACKOFF_SEC=600

export AGZ_DISTRIBUTED_EVAL_GAME_MEMORY_GIB=1.5
export AGZ_DISTRIBUTED_EVAL_MEMORY_RESERVE_GIB=18.5
export AGZ_DISTRIBUTED_EVAL_MEMORY_RESERVE_FRACTION=0.25
export AGZ_DISTRIBUTED_EVAL_PAUSE_SELFPLAY=1
export AGZ_DISTRIBUTED_EVAL_PAUSE_TIMEOUT_SEC=30
export AGZ_DISTRIBUTED_EVAL_ROLE_THREADS_PER_GAME=1
export AGZ_DISTRIBUTED_EVAL_SJF_THREADS_PER_GAME=1
export AGZ_DISTRIBUTED_EVAL_CPU_RESERVE_CORES=0
export AGZ_DISTRIBUTED_EVAL_CPU_RESERVE_FRACTION=0
export AGZ_DISTRIBUTED_EVAL_CPU_SAMPLE_SEC=0.25
export AGZ_DISTRIBUTED_EVAL_XL_GAMES=32
export AGZ_DISTRIBUTED_EVAL_XL_PARALLEL=60
export AGZ_DISTRIBUTED_EVAL_XL_CPUSET=4-95
export AGZ_DISTRIBUTED_EVAL_WORKER_PARALLEL=60
export AGZ_DISTRIBUTED_EVAL_WORKER_CPUSET=2-95
export AGZ_DISTRIBUTED_EVAL_SJF_WORKER_GAMES=5
export AGZ_DISTRIBUTED_EVAL_SJF_HOST_PARALLEL=12

export OMP_NUM_THREADS=1
export OPENBLAS_NUM_THREADS=1
export MKL_NUM_THREADS=1
